// invitados.js  (SIN type="module")
window.invitados = {
  '1': { nombre: 'Señor Rubén Lucas', pases: 1 },
  '2': { nombre: 'Familia Lucas Marroquín', pases: 4 },
  '3': { nombre: 'Familia Lucas Bonilla', pases: 4 },
  '4': { nombre: 'Familia Carpio Mazariegos', pases: 2 },
  '5': { nombre: 'Familia Cruz Carpio', pases: 4 },
  '6': { nombre: 'Familia Morales Tepeque', pases: 5 },
  '7': { nombre: 'Licda. Victoria García', pases: 1 },
  '8': { nombre: 'Licda. Brenet Hernández', pases: 2 },
  '9': { nombre: 'Familia Chinchilla Giulia y Ofelia', pases: 5 },
  '10': { nombre: 'Familia Hernández Lucas', pases: 4 },
  '11': { nombre: 'Familia Arriaza España', pases: 3 },
  '12': { nombre: 'Familia Mazariesgos Melgarejo', pases: 3 },
  '13': { nombre: 'Familia Urizar Mazariegos', pases: 2 },
  '14': { nombre: 'Familia Méndez Arriaza', pases: 4 },
  '15': { nombre: 'Belia Hernández', pases: 1 },
  '16': { nombre: 'Familia Bonilla', pases: 5 },
  '17': { nombre: 'Familia Hernández Cruz', pases: 3 },
  '18': { nombre: 'Maritza Hernández e hija', pases: 2 },
  '19': { nombre: 'Familia Anleu Hernández', pases: 6 },
  '20': { nombre: 'Familia Dubon Cruz', pases: 3 },
  '21': { nombre: 'Edgar Ruíz', pases: 1 },
  '22': { nombre: 'Familia Farfán Enríquez', pases: 4 },
  '23': { nombre: 'Familia Méndez Farfán', pases: 4 },
  '24': { nombre: 'Familia Farfán Menéndez', pases: 5 },
  '25': { nombre: 'Flor de María Ortiz', pases: 1 },
  '26': { nombre: 'Ángel Girón y fam.', pases: 4 },
  '27': { nombre: 'Mirna Odilia Ortiz', pases: 1 },
  '28': { nombre: 'Dra. Monterroso y fam.', pases: 4 },
  '29': { nombre: 'Glendy Farfán y fam.', pases: 5 },
  '30': { nombre: 'Magaly Farfán y fam.', pases: 4 },
  '31': { nombre: 'Familia Maldonado Castillo', pases: 5 },
  '32': { nombre: 'Julio Ramiro', pases: 2 },
  '33': { nombre: 'Cori de la Rosa', pases: 2 },
  '34': { nombre: 'Yako Ibarra', pases: 2 },
  '35': { nombre: 'Familia Sandoval', pases: 4 },
  '36': { nombre: 'Silvia Ramos', pases: 1 },
  '37': { nombre: 'Loly Gonzáles', pases: 1 },
  '38': { nombre: 'Juanita Núñez', pases: 2 },
  '39': { nombre: 'Señora Vanesa Ortiz e hijas', pases: 3 },
  '40': { nombre: 'Ariza Gámez', pases: 1 },
  '41': { nombre: 'Marjorie Sevilla', pases: 1 },
  '42': { nombre: 'Emilia García', pases: 1 },
  '43': { nombre: 'Samantha Torres', pases: 1 },
  '44': { nombre: 'Fátima Sosa', pases: 1 },
  '45': { nombre: 'Ximena Leonardo', pases: 1 },
  '46': { nombre: 'Emily Martínez', pases: 1 },
  '47': { nombre: 'Nicolle Cade', pases: 1 },
  '48': { nombre: 'Carlos Bonilla', pases: 1 },
  '49': { nombre: 'Danika Lorenzana', pases: 1 },
  '50': { nombre: 'Isabella Pineda', pases: 1 },
  '51': { nombre: 'Ximena Valdéz', pases: 1 },
  '52': { nombre: 'Valeria Urquijo', pases: 1 },
  '53': { nombre: 'Emilia Medina', pases: 1 },
  '54': { nombre: 'Daphne Gómez', pases: 1 },
  '55': { nombre: 'Sabrina Solano', pases: 1 },
  '56': { nombre: 'Fátima Valenzuela', pases: 1 },
  '57': { nombre: 'Dulce Altan', pases: 1 },
  '58': { nombre: 'Fabiola Dardón', pases: 1 },
  '59': { nombre: 'Antonella Urbina', pases: 1 },
  '60': { nombre: 'Michelle Berganza', pases: 1 },
  '61': { nombre: 'Pablo Vela', pases: 1 },
  '62': { nombre: 'Andrea Monterroso', pases: 1 },
  '63': { nombre: 'Valentina Moreira', pases: 1 },
  '64': { nombre: 'Karla Ralda', pases: 1 },
  '65': { nombre: 'Karla Flores', pases: 1 },
  '66': { nombre: 'Dulce Elvira', pases: 1 },
  '67': { nombre: 'Stephanie Méndez', pases: 1 },
  '68': { nombre: 'Marcela Ramos', pases: 1 },
  '69': { nombre: 'Diana Álvarez', pases: 1 },
  '70': { nombre: 'Annethe Morales', pases: 1 },
  '71': { nombre: 'Camila León', pases: 1 },
  '72': { nombre: 'Paula Cuevas', pases: 1 },
  '73': { nombre: 'Isabella Fajardo', pases: 1 },
  '74': { nombre: 'Nicolle Rangel', pases: 1 },
  '75': { nombre: 'Alexa Escobar', pases: 1 },
  '76': { nombre: 'Sarah Requena', pases: 1 }
};

